name: Build Windows Installer

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read
      packages: write
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
        cache: 'pip'
    
    - name: Create directories
      run: |
        mkdir -p dist
        mkdir -p build
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller
    
    - name: Install NSIS
      uses: joncloud/makensis-action@v4
    
    - name: Build executable
      run: |
        pyinstaller --clean --noconfirm build_exe.spec
      shell: cmd
    
    - name: Build installer
      run: |
        makensis installer.nsi
      shell: cmd
    
    - name: Upload installer
      uses: actions/upload-artifact@v3
      with:
        name: WebPConverter-Setup
        path: WebPConverter_Setup.exe
        if-no-files-found: error
